server:
  port: 9000


spring:
    datasource:
        url: jdbc:mysql://192.168.4.192:3306/buss_base_center?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: root
#        password: root
        password: 123456
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
#        db-name: adi-boot
        db-name: buss_base_center

adi:
  devtools: #开发工具
    project-location: localFilePath
    developer: code-generate-tool
    table-prefix: adi_

